### ISSUE TITLE
Bugs on CV document

### ISSUE THREAD

**Issue by nelsonmestevao** [joinum/parzival#206]
![image](https://user-images.githubusercontent.com/19409687/175795784-7587c941-b076-43bf-8e9d-ecee46a293e4.png)

**Comment by laraujo7** [comment]
The dots are on purpose because it's challenging to build a grid when doing a pdf from Html. So I limited the number of characters a skill can have. I can allow more characters though.
I don't think it's possible to put a height: 100%. Because of that, I have to put the exact height of the page in cm, and I don't understand why in some cases that happens.

**Comment by nelsonmestevao** [comment]
Probably we should go with another approach other than CSS grid to not limit more than the database does. 

For test cases it should allow things like `Java Spring Boot` (the longest example I can think of).

The height is a strange bug because the height of a A4 page should not vary. Nonetheless it is something we should try to fix.
